### ISSUE TITLE
"Token required!"

### ISSUE THREAD

**Issue by tuyewxx** [SySafarila/whatsapp-gateway#2]
/login

hasilnya
"Token required!"
padahal udah masukan token di environment

kira kira kenapa ya bang?

**Comment by SySafarila** [comment]
tambahin bearer token di setiap request, isinya JWT bebas bang, contohnya ini [Contoh JWT](https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6InN5YWhydWwiLCJpYXQiOjE1MTYyMzkwMjJ9.aYhH6vwJjVGuM0OFp-sZUz6G5Euxh1yjei7rAP8HG8Y)
yg penting `JWT_SECRET` nya sesuai dengan yg ada di .env, untuk dapet file .env nya tinggal copy paste aja dari file .env.example

**Comment by SySafarila** [comment]
![image](https://github.com/SySafarila/whatsapp-gateway/assets/57931052/67748dc5-88d6-4a8a-9c72-b93af71c87c3)
pas generate jwt, `secret base64 encoded` nya jangan di ceklis

**Comment by SySafarila** [comment]
kalo masih ada pertanyaan lain, boleh open issue baru ya
